import './globals.scss'
import type { Metadata } from 'next'
import { Encode_Sans } from 'next/font/google'

const encode = Encode_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ArchType::Editor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={encode.className}>{children}</body>
    </html>
  )
}
